version: ~> 1.0
language: shell
os: linux
dist: xenial
services:
  - docker
before_install:
  - docker build -t anatoliygatt/cicd-docker-api-test ./api
script:
  - docker run anatoliygatt/cicd-docker-api-test npm test
after_success:
  - ./publish.sh
