language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t anatoliygatt/cicd-docker-api-test ./api
script:
  - docker run anatoliygatt/cicd-docker-api-test npm test
deploy:
  provider: script
  script: ./deploy.sh
  on:
    tags: true
