version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres_password
  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    depends_on:
      - api
    ports:
      - "3000:80"
  api:
    container_name: api
    build: ./api
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
      - ./api:/app
    command: npm run dev
